//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceManagement.Areas.Login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int LoginID { get; set; }

        [Required(ErrorMessage = "Enter the UserName.")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Enter the PassWord.")]
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> PasswordReset { get; set; }
        public string MemberID { get; set; }
        public string AgentCode { get; set; }
    }
}
